# Generated by Django 2.0.7 on 2018-07-05 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100, verbose_name='旅行团名称')),
                ('text', models.CharField(max_length=200, null=True, verbose_name='旅行团备注')),
                ('route1', models.CharField(max_length=200, null=True, verbose_name='行程1')),
                ('route2', models.CharField(max_length=200, null=True, verbose_name='行程2')),
                ('route3', models.CharField(max_length=200, null=True, verbose_name='行程3')),
                ('route4', models.CharField(max_length=200, null=True, verbose_name='行程4')),
                ('route5', models.CharField(max_length=200, null=True, verbose_name='行程5')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='建立时间')),
                ('date_start', models.DateField(verbose_name='出发日期')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行团名称',
                'verbose_name_plural': '旅行团名称',
            },
        ),
    ]
